### ISSUE TITLE
Add dockerhub automated build

### ISSUE THREAD

**Issue by brandonkal** [krish512/ReviveDockerImage#2]
Awesome work.

This would be a great improvement as it looks like this was updated recently but not pushed to docker hub in 7 months.

Thank you

**Comment by krish512** [comment]
Cannot convert an existing repo to automated builds, do you know any way to do this?

**Comment by brandonkal** [comment]
@krish512 

The way I have done this before is to delete the repo from Docker Hub and then set up an automated build with the same name. This way nothing breaks for those who pull.

**Comment by krish512** [comment]
ok, thanks
