### ISSUE TITLE
Everytime I restart the container, Asking to install from the beginning

### ISSUE THREAD

**Issue by aravindmusigumpula** [krish512/ReviveDockerImage#8]
Hi,

I have run the docker image and configured some ads. But after I stopped and restarted the container, revive adserver is asking to again install the DB.
How can I avoid it.

Starting adserver with below command.
docker run  -p 801:80 -d krish512/revive

How can I skip the installation every time I restart the container.

**Comment by aravindmusigumpula** [comment]
If I install revive adserver without using this image, the above problem doesn't arise

**Comment by krish512** [comment]
You need to attach a volume so that it can persist the installed data in that volume
Revive is a stateful application and you need to ensure you store its state in a persistent storage which is available on every reboot of the container
